[database]
path = "news.db"

[archive]
path = "archive.db"
enable = true
day = 1
time_utc = "02:10"
batch_size = 1000
retention_months = 0
reindex_on_start = false
delete_from_main = false

[telegram]
bot_token = "PUT_YOUR_TOKEN_HERE"
chat_id = "PUT_CHAT_OR_USER_ID_HERE"

[scheduler]
fetch_interval_minutes = 60

[fetch]
batch_limit_per_feed = 0
timeout_seconds = 20
user_agent = "RSSBotAiogram/1.0 (+https://example.org)"

[pagination]
page_size = 10
search_page_size = 10
latest_count = 10
arc_default_limit = 10
